### ISSUE TITLE
How to start inclusive mode 

### ISSUE THREAD

**Issue by orsonwang** [ninjasphere/go-openzwave#8]
Hi 
  I have read the source code and several related project. But I cannot find any sample/code related to addNode or removeNode. Was I missing something? Please kindly give me a hint.

**Comment by jonseymour** [comment]
You might find some of the discussion in issue #6 helpful.

The basic step is that you have register a DeviceFactory with the API before you start it running. Then your Device abstraction (which you return from your factory) will receive NodeAdded() and NodeRemoved() calls whenever these events happen.

**Comment by orsonwang** [comment]
I have read it before. What bothering me is. NodeAdded() and NodeRemoved() was triggered by addNode/Remove command to controller or passive result from node. How can I call the addNode function like in cpp below
Manager::Get()->AddNode(g_homeId, false)

**Comment by jonseymour** [comment]
Orson,

Ok, so that scenario isn't catered for because I didn't believe it was needed - all nodes would be discovered rather than manually added.

Can you explain the scenario that requires you to manually add a node?

**Comment by orsonwang** [comment]
When I have a new zWave device. If I want it to join my current gateway, there are two steps to do.
1. Start inclusive mode in gateway.
2. Start the inclusion function of device.
Then they can match, the device will join the network, and gateway will return new_device_added to our program.

**Comment by jonseymour** [comment]
Right, as I understood it both of these actions require a physical interaction with two devices - the gateway and the device itself. Once that has taken place, there is no need for any API calls to complete the process - it will simply happen.

I'd be surprised if there was an API that allowed a Gateway to put a device into inclusion mode, since that defeats the physical security afforded by the need for a physical action. 

I am not aware of an API that puts the gateway into inclusion mode, though that seems more reasonable. Whether there is or not,  I am pretty sure AddNode isn't that API.

**update:** ok, I actually referred to the source this time, and I see you are correct. I'll think about how I want to expose that.

**Comment by orsonwang** [comment]
Hi 
There are gateways without any physical button. zWave protocol provide AddNode with/without security. You can see it here
http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html#a5a9a837cd066cd294fca4187b1b7c4d0

**Comment by Troy-M** [comment]
This can all be done through a openzwave controller command see [here](http://www.openzwave.com/dev/classOpenZWave_1_1Driver.html). We could easily expose the controller command API to the go package. This would allow a variety of functions such as add and remove node.

**Comment by orsonwang** [comment]
Hi Troy: Yes, but we didn't get that function in go-openwave as it was not exposed in the c interface, that's why I am asking.

**Comment by Troy-M** [comment]
This should be easy enough to implement in manager.cpp. Although I am not sure how exactly to get the homeid we will need to call BeginControllerCommand.

**Comment by orsonwang** [comment]
I have use c++ to write my system again. Let me close this for now.
